const bookDB = [
  { bookId: 1, title: 'Two States', author: 'Chetan Bhagat', price: 599, isDeleted: false },
  { bookId: 2, title: 'The Alchemist', author: 'Paulo Coelho', price: 399, isDeleted: false },
  { bookId: 3, title: 'Atomic Habits', author: 'James Clear', price: 699, isDeleted: false },
  {
    bookId: 4,
    title: 'Rich Dad Poor Dad',
    author: 'Robert Kiyosaki',
    price: 499,
    isDeleted: false,
  },
  { bookId: 5, title: 'Ikigai', author: 'Hector Garcia', price: 450, isDeleted: false },
  { bookId: 6, title: 'The Power of Now', author: 'Eckhart Tolle', price: 550, isDeleted: false },
  {
    bookId: 7,
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    price: 420,
    isDeleted: false,
  },
  { bookId: 8, title: 'Deep Work', author: 'Cal Newport', price: 620, isDeleted: false },
  {
    bookId: 9,
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    price: 530,
    isDeleted: false,
  },
  { bookId: 10, title: 'Start With Why', author: 'Simon Sinek', price: 610, isDeleted: false },
  { bookId: 11, title: 'The 5 AM Club', author: 'Robin Sharma', price: 580, isDeleted: false },
  { bookId: 12, title: 'Zero to One', author: 'Peter Thiel', price: 640, isDeleted: false },
  { bookId: 13, title: 'Sapiens', author: 'Yuval Noah Harari', price: 750, isDeleted: false },
  {
    bookId: 14,
    title: 'The Monk Who Sold His Ferrari',
    author: 'Robin Sharma',
    price: 399,
    isDeleted: false,
  },
  {
    bookId: 15,
    title: 'Wings of Fire',
    author: 'A.P.J. Abdul Kalam',
    price: 350,
    isDeleted: false,
  },
  {
    bookId: 16,
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    price: 520,
    isDeleted: false,
  },
  { bookId: 17, title: 'The Hobbit', author: 'J.R.R. Tolkien', price: 480, isDeleted: false },
  {
    bookId: 18,
    title: 'Harry Potter and the Sorcerer’s Stone',
    author: 'J.K. Rowling',
    price: 699,
    isDeleted: false,
  },
  {
    bookId: 19,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 300,
    isDeleted: false,
  },
  {
    bookId: 20,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    price: 420,
    isDeleted: false,
  },
  { bookId: 21, title: '1984', author: 'George Orwell', price: 390, isDeleted: false },
  {
    bookId: 22,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    price: 370,
    isDeleted: false,
  },
  { bookId: 23, title: 'Brave New World', author: 'Aldous Huxley', price: 410, isDeleted: false },
  { bookId: 24, title: 'The Lean Startup', author: 'Eric Ries', price: 650, isDeleted: false },
  { bookId: 25, title: 'Clean Code', author: 'Robert C. Martin', price: 820, isDeleted: false },
  {
    bookId: 26,
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt',
    price: 780,
    isDeleted: false,
  },
  {
    bookId: 27,
    title: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    price: 690,
    isDeleted: false,
  },
  { bookId: 28, title: 'You Don’t Know JS', author: 'Kyle Simpson', price: 560, isDeleted: false },
  {
    bookId: 29,
    title: 'JavaScript: The Good Parts',
    author: 'Douglas Crockford',
    price: 510,
    isDeleted: false,
  },
  { bookId: 30, title: 'Refactoring', author: 'Martin Fowler', price: 880, isDeleted: false },
  {
    bookId: 31,
    title: 'The Design of Everyday Things',
    author: 'Don Norman',
    price: 600,
    isDeleted: false,
  },
  {
    bookId: 32,
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    price: 720,
    isDeleted: false,
  },
  { bookId: 33, title: 'Grit', author: 'Angela Duckworth', price: 540, isDeleted: false },
  {
    bookId: 34,
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen Covey',
    price: 590,
    isDeleted: false,
  },
  {
    bookId: 35,
    title: 'Man’s Search for Meaning',
    author: 'Viktor Frankl',
    price: 460,
    isDeleted: false,
  },
  {
    bookId: 36,
    title: 'The Road Less Traveled',
    author: 'M. Scott Peck',
    price: 430,
    isDeleted: false,
  },
  { bookId: 37, title: 'The Art of War', author: 'Sun Tzu', price: 250, isDeleted: false },
  { bookId: 38, title: 'Meditations', author: 'Marcus Aurelius', price: 380, isDeleted: false },
  { bookId: 39, title: 'The Prince', author: 'Niccolò Machiavelli', price: 340, isDeleted: false },
  { bookId: 40, title: 'The Shining', author: 'Stephen King', price: 520, isDeleted: false },
  { bookId: 41, title: 'The Da Vinci Code', author: 'Dan Brown', price: 480, isDeleted: false },
  {
    bookId: 42,
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    price: 510,
    isDeleted: false,
  },
  {
    bookId: 43,
    title: 'The Fault in Our Stars',
    author: 'John Green',
    price: 390,
    isDeleted: false,
  },
  { bookId: 44, title: 'Gone Girl', author: 'Gillian Flynn', price: 470, isDeleted: true },
  {
    bookId: 45,
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    price: 450,
    isDeleted: false,
  },
  { bookId: 46, title: 'Dune', author: 'Frank Herbert', price: 730, isDeleted: false },
  { bookId: 47, title: 'The Martian', author: 'Andy Weir', price: 520, isDeleted: false },
  { bookId: 48, title: 'The Book Thief', author: 'Markus Zusak', price: 410, isDeleted: false },
  { bookId: 49, title: 'The Kite Runner', author: 'Khaled Hosseini', price: 460, isDeleted: false },
  { bookId: 50, title: 'Life of Pi', author: 'Yann Martel', price: 430, isDeleted: false },
  {
    bookId: 51,
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    price: 500,
    isDeleted: false,
  },
];

export default bookDB;
